name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . \
            -t ghcr.io/robingenz/docker-ionic-capacitor:latest \
            -t ghcr.io/robingenz/docker-ionic-capacitor:$(date +%Y%m%d%H%M%S)
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/robingenz/docker-ionic-capacitor --all-tags
